### ISSUE TITLE
RPC Overload

### ISSUE THREAD

**Issue by ilovespectra** [ilovespectra/solo-swap#1]
- `assetList.tsx` and `scooper.ts` contain duplicates of most functions, labeled `OG` and `Swap`:
  |-- `OG` components resolve on the assetList page to display totals in the UI
  |- - `Swap` components incorporate the user-inputed percentage to provide the quote and swap instruction with token quantities

the duplication of these functions causes RPC overload, and they will need to be isolated ad rem.

**Comment by iam-joey** [comment]
I like to work on this issue

**Comment by iam-joey** [comment]
![image](https://github.com/user-attachments/assets/e02b58e2-8ef7-4d62-83ef-1b20731d2e18)

in here sweepSwapTokens you're accepting percentage as a parameter but you're not doing anything. @ilovespectra is this anything i should  be worried about or can i proceed?

**Comment by PoulavBhowmick03** [comment]
Should we create a utils.ts to have the common functionalities and then import it in scooper.ts and assetList.tsx
@ilovespectra

**Comment by ilovespectra** [comment]
thanks for taking this on you guys! use your best judgement, i tripped over myself a bit modifying the original script, some variables are specified and no longer called. here, take a look at the original repo to see how it looked before i started meddling.

the only changes that *need* to be made to the assetlist and scooper function are creating separate quote fetch mechanisms for the UI and the swap transaction itself that incorporate the user input [percentage]. 

(the user input could also be a dollar value instead of a percentage, the percentage simply allows the quote to be made using the specified percentage of the associated token.)

https://github.com/BonkLabs/pooperscooper

**Comment by iam-joey** [comment]
Can you provide more context please the code looks bit hassle to understand. pin point the exact issue and what components are included so that i can understand it better. @ilovespectra

**Comment by ilovespectra** [comment]
the only two scripts relevant to this issue are `scooper.ts` and `assetList.tsx`, they are greatly intertwined, which was the condition i found them in. stream of consciousness in the app is as follows:

Get token accounts -> Sweep assets -> Define Swap -> Build TX 

There is an inordinate amount of moving parts between the functions, the build transaction has been modified to remove the burn, and needs to incorporate the percentage to be completed. 

If we can isolate which token queries can be removed, the RPC will be able to provide quote values in the UI. Once they're in the UI, we can tell what's going into the transaction. The wall I hit was I'm unable to get any values because of the RPC overload.

**Comment by ilovespectra** [comment]
thanks gibwork crew! this issue has been resolved
