### ISSUE TITLE
Add Stables

### ISSUE THREAD

**Issue by ilovespectra** [ilovespectra/solo-swap#2]
The UI does not currently allow the user to specify the preferred stable. 

A UI element and associated code implementation should be made that allows users to select token rather than hardcoding USDC.

Implementation should also enable users to select `%` or `$` in the UI, allowing users to enter a percentage which subsequently calculates/displays the dollar value, _or enter a dollar value which subsequently calculates the percentage used in get quote._

FOR EXAMPLE

in this image, the `%` and `$` by $20.98 (and "1") should be buttons, clicking either to swap the entry field from dollar to percentage and back, beneath $20.98, `to swap` should say `to swap to { }`...
![Screenshot 2024-07-25 at 9 54 55 AM](https://github.com/user-attachments/assets/6b26a603-0327-4471-bd4a-abb3e86d7483)
... when clicked by the user, this sort of modal be displayed, with suggested/popular tokens on top, and a search bar enabling any token be selected (bearing in mind the black/white/lowercase theme utilized throughout the dapp)
![Screenshot 2024-07-25 at 9 55 46 AM](https://github.com/user-attachments/assets/46f0d9bd-3f62-428e-a6a5-5b9f95a86e4a)

**Comment by iam-joey** [comment]
For this do we also need to integrate sweep tokens functionality based on the given stable coin? Right now I only wrote code from usdc, usdt, sol. @ilovespectra

**Comment by iam-joey** [comment]
i'm not working on this anyone feel free to pick it up

**Comment by Gmin2** [comment]
I would like to take this one 
cc @iam-joey @ilovespectra

**Comment by SOLT4NE** [comment]
working on this

**Comment by ilovespectra** [comment]
closed via gibwork. pr #10 has been merged. ty everyone. 

new bounty about to go up for slippage and priority fees
